'use client';
import {useEffect,useState} from 'react';
import Nav from '@/components/Nav';
import StatCard from '@/components/StatCard';

type Instrument={id:string;symbol:string;name:string;baseAsset:string;quoteAsset:string;price:number;leverage:number;makerFee:number;takerFee:number;enabled:boolean};

export default function Admin(){
 const [stats,setStats]=useState<any>({}); const [users,setUsers]=useState<any[]>([]); const [funds,setFunds]=useState<any[]>([]); const [positions,setPositions]=useState<any[]>([]); const [settings,setSettings]=useState<any[]>([]); const [instruments,setInstruments]=useState<Instrument[]>([]); const [audit,setAudit]=useState<any[]>([]); const [msg,setMsg]=useState('');
 const [newInstrument,setNewInstrument]=useState({symbol:'',name:'',baseAsset:'',quoteAsset:'USD',price:'1',leverage:'1',makerFee:'0.001',takerFee:'0.0015'});
 async function load(){const [a,b,c,d,e,f,g]=await Promise.all([fetch('/api/admin/stats'),fetch('/api/admin/users'),fetch('/api/admin/funding'),fetch('/api/admin/positions'),fetch('/api/admin/settings'),fetch('/api/admin/instruments'),fetch('/api/admin/audit')]);setStats(await a.json());setUsers(await b.json());setFunds(await c.json());setPositions(await d.json());setSettings(await e.json());setInstruments(await f.json());setAudit(await g.json())}
 useEffect(()=>{load();const t=setInterval(load,10000);return()=>clearInterval(t)},[]);
 async function userPatch(userId:string,field:string,value:string){const r=await fetch('/api/admin/users',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({userId,[field]:value})});setMsg(r.ok?'User updated':'Update failed');load()}
 async function forceClose(positionId:string){const r=await fetch('/api/admin/positions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({positionId})});setMsg(r.ok?'Position closed':'Force close failed');load()}
 async function saveSetting(key:string,value:string){const r=await fetch('/api/admin/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({key,value})});setMsg(r.ok?'Setting saved':'Setting failed');load()}
 async function review(id:string,decision:string){const r=await fetch('/api/admin/funding',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,decision})});const j=await r.json();setMsg(r.ok?'Funding reviewed':j.error||'Review failed');load()}
 async function instrumentPatch(id:string,data:Partial<Instrument>){const r=await fetch('/api/admin/instruments',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,...data})});setMsg(r.ok?'Instrument updated':(await r.json()).error||'Instrument update failed');load()}
 async function createInstrument(){const p={...newInstrument,price:Number(newInstrument.price),leverage:Number(newInstrument.leverage),makerFee:Number(newInstrument.makerFee),takerFee:Number(newInstrument.takerFee),enabled:true};const r=await fetch('/api/admin/instruments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(p)});const j=await r.json();setMsg(r.ok?'Instrument created':j.error||'Create failed');if(r.ok)setNewInstrument({symbol:'',name:'',baseAsset:'',quoteAsset:'USD',price:'1',leverage:'1',makerFee:'0.001',takerFee:'0.0015'});load()}
 return <><Nav/><main className="mx-auto max-w-7xl px-4 py-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="gold text-xs font-bold tracking-[.25em]">CONTROL CENTER</div><h1 className="text-3xl font-black">Aurevia administration</h1></div><a className="btn bg-white/5" href="/admin/login">Admin login</a></div>{msg&&<p className="mt-2 muted">{msg}</p>}
 <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-6"><StatCard label="Users" value={String(stats.users??0)}/><StatCard label="Executed quantity" value={Number(stats.volume??0).toFixed(4)}/> <StatCard label="Trading fees" value={`$${Number(stats.fees??0).toFixed(2)}`}/><StatCard label="Open positions" value={String(stats.positions??0)}/><StatCard label="Pending deposits" value={`$${Number(stats.deposits??0).toFixed(2)}`}/><StatCard label="Pending withdrawals" value={`$${Number(stats.withdrawals??0).toFixed(2)}`}/></div>
 <div className="mt-5 grid gap-4 lg:grid-cols-2">
  <section className="card p-5"><h2 className="font-bold">Funding queue</h2>{funds.length?funds.map(f=><div key={f.id} className="border-b border-white/10 py-4"><div className="flex justify-between gap-2"><span>{f.user.email}</span><span>{f.type} ${Number(f.amount).toFixed(2)}</span></div><div className="mt-2 flex gap-2"><button className="btn bg-profit text-black" onClick={()=>review(f.id,'APPROVED')}>Approve</button><button className="btn bg-loss" onClick={()=>review(f.id,'REJECTED')}>Reject</button></div></div>):<p className="mt-4 muted">Queue is empty.</p>}</section>
  <section className="card p-5"><h2 className="font-bold">Users</h2><div className="mt-3 max-h-[520px] overflow-auto">{users.map(u=><div key={u.id} className="border-b border-white/10 py-3"><div className="flex flex-wrap justify-between gap-2"><span>{u.email}</span><span className="muted">{u.role} · {u.kycStatus}</span></div><div className="mt-2 flex flex-wrap gap-2"><button className="btn bg-white/5" onClick={()=>userPatch(u.id,'status',u.status==='ACTIVE'?'FROZEN':'ACTIVE')}>{u.status==='ACTIVE'?'Freeze':'Unfreeze'}</button><button className="btn bg-white/5" onClick={()=>userPatch(u.id,'kycStatus','APPROVED')}>Approve KYC</button><button className="btn bg-white/5" onClick={()=>userPatch(u.id,'kycStatus','REJECTED')}>Reject KYC</button><button className="btn bg-white/5" onClick={()=>userPatch(u.id,'role',u.role==='ADMIN'?'USER':'ADMIN')}>{u.role==='ADMIN'?'Make user':'Make admin'}</button></div></div>)}</div></section>
  <section className="card p-5"><h2 className="font-bold">Open positions</h2>{positions.length?positions.map(p=><div key={p.id} className="flex items-center justify-between gap-3 border-b border-white/10 py-3"><span>{p.user.email} · {p.instrument.symbol} · {p.side}</span><button className="btn bg-loss" onClick={()=>forceClose(p.id)}>Force close</button></div>):<p className="mt-4 muted">No open positions.</p>}</section>
  <section className="card p-5"><h2 className="font-bold">Instrument management</h2><div className="mt-4 grid gap-2 sm:grid-cols-2"><input className="input" placeholder="Symbol" value={newInstrument.symbol} onChange={e=>setNewInstrument({...newInstrument,symbol:e.target.value.toUpperCase()})}/><input className="input" placeholder="Name" value={newInstrument.name} onChange={e=>setNewInstrument({...newInstrument,name:e.target.value})}/><input className="input" placeholder="Base asset" value={newInstrument.baseAsset} onChange={e=>setNewInstrument({...newInstrument,baseAsset:e.target.value.toUpperCase()})}/><input className="input" placeholder="Quote asset" value={newInstrument.quoteAsset} onChange={e=>setNewInstrument({...newInstrument,quoteAsset:e.target.value.toUpperCase()})}/><input className="input" type="number" placeholder="Price" value={newInstrument.price} onChange={e=>setNewInstrument({...newInstrument,price:e.target.value})}/><input className="input" type="number" placeholder="Leverage" value={newInstrument.leverage} onChange={e=>setNewInstrument({...newInstrument,leverage:e.target.value})}/><input className="input" type="number" step="0.000001" placeholder="Maker fee" value={newInstrument.makerFee} onChange={e=>setNewInstrument({...newInstrument,makerFee:e.target.value})}/><input className="input" type="number" step="0.000001" placeholder="Taker fee" value={newInstrument.takerFee} onChange={e=>setNewInstrument({...newInstrument,takerFee:e.target.value})}/></div><button className="btn mt-3 bg-gold text-black" onClick={createInstrument}>Add instrument</button><div className="mt-5 space-y-2">{instruments.map(i=><div key={i.id} className="rounded-xl bg-white/5 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-bold">{i.symbol} · {Number(i.price).toLocaleString()}</span><button className="btn bg-white/5" onClick={()=>instrumentPatch(i.id,{enabled:!i.enabled})}>{i.enabled?'Disable':'Enable'}</button></div><div className="mt-2 grid grid-cols-2 gap-2"><input className="input" type="number" value={i.price} onChange={e=>setInstruments(xs=>xs.map(x=>x.id===i.id?{...x,price:Number(e.target.value)}:x))}/><input className="input" type="number" value={i.leverage} onChange={e=>setInstruments(xs=>xs.map(x=>x.id===i.id?{...x,leverage:Number(e.target.value)}:x))}/></div><button className="btn mt-2 bg-white/5" onClick={()=>instrumentPatch(i.id,{price:Number(i.price),leverage:Number(i.leverage)})}>Save market settings</button></div>)}</div></section>
  <section className="card p-5"><h2 className="font-bold">System settings</h2>{settings.length?settings.map(x=><div key={x.key} className="flex items-center gap-3 border-b border-white/10 py-3"><span className="min-w-40 text-sm">{x.key}</span><input className="input" defaultValue={x.value} onBlur={e=>saveSetting(x.key,e.currentTarget.value)}/></div>):<p className="mt-4 muted">No settings yet.</p>}</section>
  <section className="card p-5 lg:col-span-2"><h2 className="font-bold">Audit log</h2><div className="mt-3 max-h-80 overflow-auto">{audit.map(x=><div key={x.id} className="border-b border-white/10 py-2 text-xs"><span>{new Date(x.createdAt).toLocaleString()}</span> · <span className="gold">{x.action}</span> · {x.entity} {x.entityId??''}</div>)}</div></section>
 </div></main></>
}
